// vocabulary-data.js
// All vocabulary data organized by lessons

const vocabularyData = [

    //Lesson 22
    { japanese: "きます [シャツを～]", meaning: "put on [a shirt, etc]", lesson: 22 },
    { japanese: "はきます [くつを～]", meaning: "put on [shoes, trousers, etc]", lesson: 22 },
    { japanese: "かぶります [ぼうしを～]", meaning: "put on [a hat, etc]", lesson: 22 },
    { japanese: "かけます [めがねを～]", meaning: "put on [glasses]", lesson: 22 },
    { japanese: "うまれます", meaning: "be born", lesson: 22 },
    { japanese: "コート", meaning: "coat", lesson: 22 },
    { japanese: "スーツ", meaning: "suit", lesson: 22 },
    { japanese: "セーター", meaning: "sweater", lesson: 22 },
    { japanese: "ぼうし", meaning: "hat, cap", lesson: 22 },
    { japanese: "めがね", meaning: "glasses", lesson: 22 },
    { japanese: "よく", meaning: "often", lesson: 22 },
    { japanese: "おめでとう ございます。", meaning: "Congratulations. (used on birthdays, at weddings, New Year's Day, etc.)", lesson: 22 },
    { japanese: "こちら", meaning: "this (polite equivalent of これ)", lesson: 22 },
    { japanese: "やちん", meaning: "house rent", lesson: 22 },
    { japanese: "うーん", meaning: "Let me see.", lesson: 22 },
    { japanese: "ダイニングキチン", meaning: "kitchen with a dining area", lesson: 22 },
    { japanese: "わしつ", meaning: "Japanese-style room", lesson: 22 },
    { japanese: "おしいれ", meaning: "Japanese-style closet", lesson: 22 },
    { japanese: "ふとん", meaning: "Japanese-style mattress and quilt", lesson: 22 },
    { japanese: "アパート", meaning: "apartment", lesson: 22 },
    { japanese: "パリ", meaning: "Paris", lesson: 22 },
    { japanese: "ばんりのちょうじょう", meaning: "The Great Wall of China", lesson: 22 },

    //Lesson 23
    { japanese: "ききます [せんせいに～]", meaning: "ask [the teacher]", lesson: 23 },
    { japanese: "まわします", meaning: "turn", lesson: 23 },
    { japanese: "ひきます", meaning: "pull", lesson: 23 },
    { japanese: "かえます", meaning: "change", lesson: 23 },
    { japanese: "さわります [ドアに～]", meaning: "touch [a door]", lesson: 23 },
    { japanese: "でます [おつりが～]", meaning: "[change] come out", lesson: 23 },
    { japanese: "うごきます [とけいが～]", meaning: "[a watch] move, work", lesson: 23 },
    { japanese: "あるきます [みちを～]", meaning: "walk [along a road]", lesson: 23 },
    { japanese: "わたります [はしを～]", meaning: "cross [a bridge]", lesson: 23 },
    { japanese: "きをつけます [くるまに～]", meaning: "pay attention [to cars], take care", lesson: 23 },
    { japanese: "ひっこしします", meaning: "move (house)", lesson: 23 },
    { japanese: "でんきや", meaning: "electrician", lesson: 23 },
    { japanese: "～や", meaning: "person of ~ shop", lesson: 23 },
    { japanese: "サイズ", meaning: "size", lesson: 23 },
    { japanese: "おと", meaning: "sound", lesson: 23 },
    { japanese: "きかい", meaning: "machine", lesson: 23 },
    { japanese: "つまみ", meaning: "knob", lesson: 23 },
    { japanese: "こしょう", meaning: "breakdown (～します: breakdown)", lesson: 23 },
    { japanese: "みち", meaning: "road, way", lesson: 23 },
    { japanese: "こうさてん", meaning: "crossroad", lesson: 23 },
    { japanese: "しんごう", meaning: "traffic light", lesson: 23 },
    { japanese: "かど", meaning: "corner", lesson: 23 },
    { japanese: "はし", meaning: "bridge", lesson: 23 },
    { japanese: "ちゅうしゃじょう", meaning: "parking lot, car park", lesson: 23 },
    { japanese: "－め", meaning: "the -th (indicating order)", lesson: 23 },
    { japanese: "[お] しょうがつ", meaning: "New Year's Day", lesson: 23 },
    { japanese: "ごちそうさま [でした]。", meaning: "That was delicious. (Said after eating or drinking)", lesson: 23 },
    { japanese: "たてもの", meaning: "building", lesson: 23 },
    { japanese: "がいこくじんとうろくしょう", meaning: "alien registration card", lesson: 23 },
    { japanese: "しょうとくたいし", meaning: "Prince Shotoku (574-622)", lesson: 23 },
    { japanese: "ほうりゅうじ", meaning: "Horyuji Temple", lesson: 23 },
    
    // Lesson 24
    { japanese: "くれます", meaning: "give (me)", lesson: 24 },
    { japanese: "つれていきます", meaning: "take (someone)", lesson: 24 },
    { japanese: "つれてきます", meaning: "bring (someone)", lesson: 24 },
    { japanese: "おくります [ひとを～]", meaning: "escort [someone], go with", lesson: 24 },
    { japanese: "しょうかいします", meaning: "introduce", lesson: 24 },
    { japanese: "あんないします", meaning: "show around, show the way", lesson: 24 },
    { japanese: "せつめいします", meaning: "explain", lesson: 24 },
    { japanese: "いれます [コーヒーを～]", meaning: "make [coffee]", lesson: 24 },
    { japanese: "おじいさん／おじいちゃん", meaning: "grandfather, old man", lesson: 24 },
    { japanese: "おばあさん／おばあちゃん", meaning: "grandmother, old woman", lesson: 24 },
    { japanese: "じゅんび", meaning: "preparation (～します: prepare)", lesson: 24 },
    { japanese: "いみ", meaning: "meaning", lesson: 24 },
    { japanese: "[お] かし", meaning: "sweets, snacks", lesson: 24 },
    { japanese: "ぜんぶ", meaning: "all", lesson: 24 },
    { japanese: "じぶんで", meaning: "by oneself", lesson: 24 },
    { japanese: "ほかに", meaning: "besides", lesson: 24 },
    { japanese: "ワゴンしゃ", meaning: "station wagon", lesson: 24 },
    { japanese: "[お] べんとう", meaning: "box lunch", lesson: 24 },
    { japanese: "ははのひ", meaning: "Mother's Day", lesson: 24 },
    
    // Lesson 25
    { japanese: "かんがえます", meaning: "think, consider", lesson: 25 },
    { japanese: "つきます [えきに～]", meaning: "arrive [at the station]", lesson: 25 },
    { japanese: "りゅうがくします", meaning: "study abroad", lesson: 25 },
    { japanese: "とります [としを～]", meaning: "grow old", lesson: 25 },
    { japanese: "いなか", meaning: "countryside, hometown", lesson: 25 },
    { japanese: "たいしかん", meaning: "embassy", lesson: 25 },
    { japanese: "グループ", meaning: "group", lesson: 25 },
    { japanese: "チャンス", meaning: "chance", lesson: 25 },
    { japanese: "おく", meaning: "hundred million", lesson: 25 },
    { japanese: "もし [～たら]", meaning: "if ~", lesson: 25 },
    { japanese: "いくら [～ても]", meaning: "however ~, even if ~", lesson: 25 },
    { japanese: "てんきん", meaning: "transfer (～します: be transferred to another office)", lesson: 25 },
    { japanese: "こと", meaning: "thing, matter (～のこと: thing about ~)", lesson: 25 },
    { japanese: "いっぱいのみましょう。", meaning: "Let's have a drink together.", lesson: 25 },
    { japanese: "[いろいろ] お世話になりました。", meaning: "Thank you for everything you have done for me.", lesson: 25 },
    { japanese: "がんばります", meaning: "do one's best", lesson: 25 },
    { japanese: "どうぞお元気で。", meaning: "Best of luck. (said when expecting a long separation)", lesson: 25 }
];

// You can add more lessons here as you progress
// Example for future lessons:
// { japanese: "word", meaning: "meaning", lesson: 1 },
// { japanese: "word", meaning: "meaning", lesson: 2 },
// etc...